=== martin131/CZU_znacJaz/matuna_znacJaz.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="moviesInPocket">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="settings">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="basicSettings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="language"/>
                    <xs:element type="xs:string" name="dateFormat"/>
                    <xs:element type="xs:string" name="theme"/>
                    <xs:element type="xs:boolean" name="fastStartup"/>
                    <xs:element type="xs:string" name="font"/>
                    <xs:element type="xs:byte" name="fontSize"/>
                    <xs:element type="xs:string" name="tmpLocation"/>
                    <xs:element type="xs:int" name="maxCacheSize"/>
                    <xs:element type="xs:byte" name="logoutAfter"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="userSettings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="username"/>
                    <xs:element type="xs:string" name="password"/>
                    <xs:element type="xs:boolean" name="saveLogin"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="systemSettings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="protocol"/>
                    <xs:element type="xs:string" name="allowSecureConnection"/>
                    <xs:element type="xs:string" name="serverUrl"/>
                    <xs:element type="xs:string" name="urlPath"/>
                    <xs:element type="xs:string" name="streamUrl"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element name="playerSettings">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:short" name="defaultBitrate"/>
                    <xs:element type="xs:string" name="defaultLanguage"/>
                    <xs:element type="xs:string" name="defaultRatio"/>
                    <xs:element type="xs:byte" name="defaultZoom"/>
                    <xs:element type="xs:boolean" name="subtitleEnabled"/>
                    <xs:element type="xs:string" name="defaultSubtitleLanguage"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="rights">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="right" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:boolean" name="login"/>
                    <xs:element type="xs:boolean" name="play"/>
                    <xs:element type="xs:boolean" name="delete"/>
                    <xs:element type="xs:boolean" name="admin"/>
                    <xs:element type="xs:boolean" name="ageLimit"/>
                    <xs:element type="xs:string" name="name"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="rid" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="genres">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="genre" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="gid" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="movies">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="movie" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:short" name="year"/>
                    <xs:element type="xs:string" name="country"/>
                    <xs:element type="xs:byte" name="genre"/>
                    <xs:element type="xs:byte" name="rating"/>
                    <xs:element type="xs:string" name="director"/>
                    <xs:element type="xs:string" name="description"/>
                    <xs:element type="xs:boolean" name="streamAvailable"/>
                    <xs:element name="languages">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="language" maxOccurs="unbounded" minOccurs="0">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                                  <xs:attribute type="xs:string" name="code" use="optional"/>
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:short" name="bitrate"/>
                    <xs:element type="xs:byte" name="ageLimit"/>
                    <xs:element type="xs:string" name="releaseDate"/>
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="optional"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
    <!-- Nastavení omezení -->
  <xs:simpleType name="vypzap"> <!-- Omezení zapnuto/vypnuto -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="1"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="chars"> <!-- Omezení nastavení charsetu -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="utf-8"/>
      <xs:enumeration value="windows-1258"/>
      <xs:enumeration value="utf-7"/>
      <xs:enumeration value="iso-8859"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="jaz"> <!-- Omezení nastavení jazyku -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="CZ"/>
      <xs:enumeration value="EN"/>
      <xs:enumeration value="US"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="prot"> <!-- Omezení nastavení protokolů -->
    <xs:restriction base="xs:string">
      <xs:enumeration value="http"/>
      <xs:enumeration value="https"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="email"> <!-- Omezení nastavení emailových adres -->
    <xs:restriction base="xs:string">
       <xs:pattern value="[^@]+@[^\.]+\..+"/> <!-- Regex pro rozpoznání emailové adresy -->
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="oprav"><!-- Omezení nastavení oprávnění-->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="3"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="pop"><!-- Omezení nastavení popisu sekce-->
    <xs:restriction base="xs:string">
    	<xs:minLength value="10"/>
      	<xs:maxLength value="150"/>
    </xs:restriction>
  </xs:simpleType> 
  <xs:simpleType name="Vek-omezeni"> <!-- Omezení nastavení věkového omezení -->
    <xs:restriction base="xs:integer">
      <xs:minInclusive value="0"/>
      <xs:maxInclusive value="18"/>
    </xs:restriction>
  </xs:simpleType> 
</xs:schema>

=== martin131/CZU_znacJaz/matuna_znacJaz.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Copyright 2017 Martin Matuna -->
<?xml-stylesheet type="text/xsl" href="matuna_znacJaz.xsl"?>
<moviesInPocket xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="matuna_znacJaz.xsd">
  <settings>
    <basicSettings>
      <language>english</language>
      <dateFormat>dd-mm-rrrr</dateFormat>
      <theme>dark</theme>
      <fastStartup>no</fastStartup>
      <font>Comic Sans</defaultFont>
      <fontSize>12</defaultFontSize>
      <location>C:\\Zemedelec</defaultLocation>
      <maxCacheSize>50000</maxCacheSize>
      <logoutAfter>5</logoutAfter>
    </basicSettings>
    <userSettings>
      <username>user</username>
      <password>123456</password>
      <saveLogin>true</saveLogin>
    </userSettings>
    <systemSettings>
      <protocol>https</protocol>
      <allowSecureConnection>TRUE</allowSecureConnection>
      <serverUrl>server.nekde.com</serverUrl>
      <urlPath>v1.1</urlPath>
      <streamUrl>streamserver.nekde.com</streamUrl>
    </systemSettings>
    <playerSettings>
      <defaultBitrate>2500</defaultBitrate>
      <defaultLanguage>cs</defaultLanguage>
      <defaultRatio>16:9</defaultRatio>
      <defaultZoom>1</defaultZoom>
      <subtitleEnabled>true</subtitleEnabled>
      <defaultSubtitleLanguage>cs</defaultSubtitleLanguage>
    </playerSettings>
  </settings>
  <rights>
    <right name="user" id="1">
      <login>1</login>
      <play>1</play>
      <delete>0</delete>
      <admin>0</admin>
      <ageLimit>0</ageLimit>
    </right>
    <right name="children" id="2">
      <login>1</login>
      <play>1</play>
      <delete>0</delete>
      <admin>0</admin>
      <ageLimit>15</ageLimit>
    </right>
    <right name="admin" id="2">
      <login>1</login>
      <play>1</play>
      <delete>1</delete>
      <admin>1</admin>
      <ageLimit>0</ageLimit>
    </right>
  </rights>
  <genres>
    <genre id="1">
      <name>Comedy</name>
    </genre>
    <genre id="2">
      <name>Action</name>
    </genre>
    <genre id="3">
      <name>Thriller</name>
    </genre>
    <genre id="4">
      <name>Horror</name>
    </genre>
    <genre id="5">
      <name>Cartoon</name>
    </genre>
    <genre id="6">
      <name>Sci-fi</name>
    </genre>
  </genres>
  <movies>
    <movie id="1">
      <name>Vykoupení z věznice Shawshank</name>
      <year>1994</year>
      <country>USA</country>
      <genre>5</genre>
      <rating>95</rating>
      <director>Frank Darabont</director>
      <description>Strach dělá z lidá vězně. Naděje jim dává křídla. Film natočený podle novely Stephena Kinga.</description>
      <streamAvailable>1</streamAvailable>
      <languages>
        <language id="1" code="cs"></language>
        <language id="2" code="en"></language>
      </languages>
      <bitrate>10000</bitrate>
      <ageLimit>15</ageLimit>
      <releaseDate>5-9-2004</releaseDate>
    </movie>
    <movie id="2">
      <name>Forrest Gump</name>
      <year>1994</year>
      <country>USA</country>
      <genre>3</genre>
      <rating>95</rating>
      <director>Robert Zemeckis</director>
      <description>Zemeckisův film je brilantním shrnutím dosavadních režisérových poznatků o možnostech "comicsového" vyprávění.</description>
      <streamAvailable>1</streamAvailable>
      <languages>
        <language id="1" code="sk"></language>
        <language id="2" code="en"></language>
      </languages>
      <bitrate>15000</bitrate>
      <ageLimit>15</ageLimit>
      <releaseDate>28-3-2001</releaseDate>
    </movie>
    <movie id="3">
      <name>Zelená míle</name>
      <year>1999</year>
      <country>USA</country>
      <genre>2</genre>
      <rating>95</rating>
      <director>Frank Darabont</director>
      <description>Na začátku příběhu se potkáme se starým mužem Paulem Edgecombem (Dabbs Greer).</description>
      <streamAvailable>1</streamAvailable>
      <languages>
        <language id="1" code="cs"></language>
        <language id="2" code="en"></language>
        <language id="3" code="de"></language>
      </languages>
      <bitrate>10000</bitrate>
      <ageLimit>0</ageLimit>
      <releaseDate>1-1-2015</releaseDate>
    </movie>
  </movies>
</moviesInPocket>
